### ISSUE TITLE
Galaxy Interactive Environments (GIEs)

### ISSUE THREAD

**Issue by mictadlo** [mpg-age-bioinformatics/galaxy-admin#1]
Hello,
Were you able to get Galaxy Interactive Environments (GIEs) running with your setup? I found few links about it:
- https://github.com/galaxyproject/ansible-interactive-environments
- https://wiki.galaxyproject.org/Admin/GIEs

Thank you in advance

Mic

**Comment by setempler** [comment]
Dear Mic,

thank you very much for your interest. 

We did not implement GIEs into our instance, since we have e.g. RStudio and iPython notebooks running separately. In case you found a way to implement this, feel free to share your solution. For now, I will close the issue, please open a new one if you like to drop further notes.

Best wishes,
Sven
